---
version: '3.4'
services:
  cantaloupe:
    image: nulib/cantaloupe
    build: "./cantaloupe"
  fedora:
    image: nulib/fcrepo4
    build: "./fcrepo"
  localstack:
    image: localstack/localstack
    build: "./localstack"
  rails:
    image: nulib/rails
    build: "./rails"
  sqsd:
    image: nulib/sqsd
    build: "./sqsd"
  zookeeper:
    image: nulib/zookeeper
    build: './zookeeper'
